sudo: required

language: generic

services:
  - docker

install:
  - docker pull sinoru/swiftenv:latest

script:
  - docker build -t sinoru/swift .
  - docker ps -a

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag sinoru/swift sinoru/swift:latest;
    docker push sinoru/swift;
    fi